services:
  llm_indexer:
    build: ./llm_indexer
    ports:
      - "8000:8000"
    env_file:
      - .env
  discordjs-bot:
    build: .
    volumes:
      - ${PWD}/.env.prod:/var/www/.env.prod
    restart: unless-stopped
    
