services:
  llm_indexer:
    build: ./llm_indexer
    env_file:
      - .env
    volumes:
      - ${PWD}/llm_indexer:/var/www
    networks:
      - private
  discordjs-bot:
    build: .
    volumes:
      - ${PWD}:/var/www
      - ${PWD}/.env.prod:/var/www/.env.prod
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - public
      - private
  redis:
    image: redis:alpine
    command: |
      redis-server /usr/local/etc/redis/redis.conf
    env_file:
      - .env
    volumes:
      - ${PWD}/redis:/var/lib/redis
      - ${PWD}/redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
    networks:
      - private
  mongodb:
    image: mongo:latest
    env_file:
      - .env
    volumes:
      - ${PWD}/mongodb:/data/db
    networks:
      - private
  mongo-express:
    image: mongo-express
    restart: always
    env_file:
      - .env
    ports:
      - 8081:8081
    networks:
      - private

networks:
  public:
    driver: bridge
  private:
    driver: bridge
    internal: true
