services:
  llm_indexer:
    build: ./llm_indexer
    env_file:
      - .env
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - ${PWD}/llm_indexer:/var/www
  discordjs-bot:
    build: .
    volumes:
      - ${PWD}:/var/www
      - ${PWD}/.env:/var/www/.env
    restart: unless-stopped
    depends_on:
      - redis
  redis:
    image: redis:alpine
    command: |
      redis-server /usr/local/etc/redis/redis.conf
    env_file:
      - .env
    volumes:
      - ${PWD}/redis:/var/lib/redis
      - ${PWD}/redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
  mongodb:
    image: mongo:latest
    env_file:
      - .env
    volumes:
      - ${PWD}/mongodb:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    env_file:
      - .env
    ports:
      - 127.0.0.1:8081:8081
