services:
  llm_indexer:
    build: ./llm_indexer
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ${PWD}/llm_indexer:/var/www
  discordjs-bot:
    build: .
    volumes:
      - ${PWD}:/var/www
      - ${PWD}/.env.prod:/var/www/.env.prod
    restart: unless-stopped
    depends_on:
      - redis
  redis:
    image: redis:alpine
    command: |
      redis-server /usr/local/etc/redis/redis.conf
    env_file:
      - .env
    volumes:
      - ${PWD}/redis:/var/lib/redis
      - ${PWD}/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    restart: always
  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - ${PWD}/mongodb:/data/db
