export const whitelistNotRequired =`👋 Hey! In preparation for Testnet {4}, we've launched a Genesis Node Operators Application form to collect node specification details from Node Operators.

The Testnet Phase {4} introduces the Fleek Network Genesis Operators (GO’s), comprising approximately 50-100 initial node operators selected by the Foundation based on both merit and geographic location to operate nodes during the Phase {4} testnet–the Fleek team will reach out to the selected node operators. Stay informed by checking the blog for updates on the selection process. If you haven't been contacted, it indicates that you were not selected.

For any further conditions and rules to operate a node, you'll have to check our <https://blog.fleek.network> and documentation <https://docs.fleek.network> to learn more, please 🙏`;

export const warningAssistedAI =
  "-----------------------------------\n\n🤖 Please note that this text was generated by an AI-powered assistant. While we try to provide accurate and helpful information, it's always advisable to double-check with original knowledge sources, e.g. docs.";

// Warning: the text literal lack of indentation has a purpose, do not change
export const infoHowGetHelp = `👀 Hey $author!

\r\n**How to Get Help**
- Before asking: Try to find the solution yourself. (CTRL + F in this server can answer a lot of questions)
- Skip "I need help", "Help please", "Can I ask a thing", "I have an error" - Yes you can! Getting help is what this server is for!

**Help Us to Help You**
- Imagine you are the one trying to help. Ask the question in a way that you would want to read!
- Try to find the answer in the documentation site, e.g. use the search option
- Read the responses you are given.
- Research key words you do not understand before asking what they mean. (come back and ask, if you cannot find them)

**No Answer?**
- Do not mention uninvolved people to get a response.
- Try to give more context / improve your description.
- Try to find a solution yourself while waiting
- Try to rephrase your question.

**Chat commands**
- !search <query> e.g. !search how to install
- !ask <query> e.g. !ask how to do a healthcheck

👆 The commands only work in the Fleek Network channels

**To learn more visit:**
<https://docs.fleek.network>

**For Node Operator options tools run:**
\`\`\`
curl https://get.fleek.network | bash
\`\`\``;

export const visitDocsSite = `👋 Hey $user, visit the documentation site at $docsSite`;

export const foundResults = `👋 Hey! Found the following results:\n\n $answer`;

export const searchFor = `Search for $query`;

export const queryReceivedPleaseWait = `👀 Hey $user received the query "$query", please be patient while I check...`;

export const lookingForHelp = `Looking for help?`;

export const onAskSucceededResponseMsg = `👋 Hey $user $response\n\n$warningAssistedAI`;

export const aboutWhitelisting = `About whitelisting`;

export const anyoneCanInstall = `👀 Hey $author, anyone can install and run node! Check the requirements and instructions in <https://docs.fleek.network/docs/node/install>`;

export const nodeSetup = `Node setup`;

export const lookingForRoles = `👀 Hey $author, if you are looking for roles, go to <id:customize> to pick roles. Roles open access to channels you might be interested in, so make sure to pick the correct roles.`;

export const channelsRoles = `Channels and Roles`;

export const lookingForRewards = `👀 Hey $author, seems that you are talking about incentives or rewards?

We're working hard to make sure that the rewards mechanism is top-notch before we roll it out. Our team takes great care to deploy and test under the testnet, but it's important to note that the testnet is not incentivized. Therefore, rewards and incentives will only be available on the mainnet after passing rigorous tests.

Rest assured, we're doing everything we can to make sure that you'll be rewarded for your efforts.

To learn more visit the documentation site https://docs.fleek.network, thanks for your patience and understanding!`;

export const incentivesRewards = `Incentives and Rewards`;

export const isNodeWorking = `👀 Hey $author, to verify if your node is running correctly do a health checkup!

To do a health check run the command in the server:

\`\`\`
curl -sS https://get.fleek.network/healthcheck | bash
\`\`\`

To learn more visit https://docs.fleek.network/docs/node/health-check`;

export const healthCheckups = `Health checkups`;

export const analyzingLogsLearnMore = `👀 Hey $author, if you'd like to learn about logs visit the documentation https://docs.fleek.network/docs/node/analyzing-logs but in general, a health checkup is all you have to do! The logs are useful mostly you are troubleshooting issues, asserting something or developing.

To run a health check do:

\`\`\`
curl -sS https://get.fleek.network/healthcheck | bash
\`\`\`

To learn more visit https://docs.fleek.network/docs/node/health-check`;

export const analyzingLogs = `Analyzing logs`;

export const canSomeoneHelp = `👀 Hey $author, have you tried typing **!help** command in the channel to find the different ways to get help? If you have done that already, be patient, thank you!`;

export const whenNextTestnet = `👀 Hey $author, for testnet announcements and requirements you have to keep an eye in the announcements in <#994686135789953106> and <#1148719641896693873>. You can also check the roadmap in our docs here <https://docs.fleek.network/docs/roadmap/>.
      
Alternatively, you can keep visit our Blog site (<https://blog.fleek.network/>) or follow us on Twitter (<https://twitter.com/fleek_net>).
      
Thanks for your patience and understanding!`;

export const aboutNextTestnetPhase = "About next testnet phase";

export const forGreetingsUse = `$author for greetings use the channel <#$discordChannelIdGmGn>`;
