export const whitelistNotRequired =
  "👋 Hey! Since the Testnet Phase {1}, that all users are free to set up and run a node. There hasn't been any whitelisting since and until further notice, you shouldn't be worried. Read our <https://blog.fleek.network> and check our documentation <https://docs.fleek.network> to learn more, please 🙏";

export const warningAssistedAI =
  "-----------------------------------\n\n🤖 Please note that this text was generated by an AI-powered assistant. While we try to provide accurate and helpful information, it's always advisable to double-check with original knowledge sources, e.g. docs.";

// Warning: the text literal lack of indentation has a purpose, do not change
export const infoHowGetHelp = `👀 Hey $author!

\r\n**How to Get Help**
- Before asking: Try to find the solution yourself. (CTRL + F in this server can answer a lot of questions)
- Skip "I need help", "Help please", "Can I ask a thing", "I have an error" - Yes you can! Getting help is what this server is for!

**Help Us to Help You**
- Imagine you are the one trying to help. Ask the question in a way that you would want to read!
- Try to find the answer in the documentation site, e.g. use the search option
- Read the responses you are given.
- Research key words you do not understand before asking what they mean. (come back and ask, if you cannot find them)

**No Answer?**
- Do not mention uninvolved people to get a response.
- Try to give more context / improve your description.
- Try to find a solution yourself while waiting
- Try to rephrase your question.

**Chat commands**
- !search <query> e.g. !search how to install
- !ask <query> e.g. !ask how to do a healthcheck

👆 The commands only work in the Fleek Network channels

**To learn more visit:**
<https://docs.fleek.network>

**For Node Operator options tools run:**
\`\`\`
curl https://get.fleek.network | bash
\`\`\``;

export const visitDocsSite = `👋 Hey $user, visit the documentation site at $docsSite`;

export const foundResults = `👋 Hey! Found the following results:\n\n $answer`;

export const searchFor = `Search for $query`;

export const queryReceivedPleaseWait = `👀 Hey $user received the query "$query", please be patient while I check...`;

export const lookingForHelp = `Looking for help?`;

export const onAskSucceededResponseMsg = `👋 Hey $user $response\n\n$warningAssistedAI`;

export const aboutWhitelisting = `About whitelisting`;

export const anyoneCanInstall = `👀 Hey $author, anyone can install and run node! Check the requirements and instructions in <https://docs.fleek.network/docs/node/install>`;

export const nodeSetup = `Node setup`;
