#!/bin/bash

targetBranch="develop"
wrkDir="/home/discord/droidscord"

cd "$wrkDir" || exit 1

if ! git checkout "$targetBranch"; then
  echo "👹 Oops! Failed to switch branch"

  exit 1
fi

if ! git fetch origin || ! git reset --hard "origin/$targetBranch"; then
  echo "👹 Oops! Failed to clear stage"

  exit 1
fi

git clean -f

if ! docker compose ps --format "{{.Service}} {{.State}}" | grep 'llm_indexer running' || ! docker compose ps --format "{{.Service}} {{.State}}" | grep 'discordjs-bot'; then
  echo "⚠️  Warrning: Docker compose stack is down"
  echo "🤖 Should start compose stack, be patient..."

  if ! docker compose up -d; then
    echo "👹 Oops! Failed to start compose stack"

    exit 1
  fi
fi


if ! docker compose restart; then
  echo "👹 Oops! Failed to restart docker compose"

  exit 1
fi
