#!/bin/bash

targetBranch="develop"
wrkDir="/home/discord/droidscord"

cd "$wrkDir" || exit 1

if ! git checkout "$targetBranch"; then
  echo "👹 Oops! Failed to switch branch"

  exit 1
fi

if ! git fetch origin || ! git reset --hard "origin/$targetBranch"; then
  echo "👹 Oops! Failed to clear stage"

  exit 1
fi

git clean -f

echo "[INFO] Current commit"
git show --oneline -s

echo "[INFO] Update packages"
if ! npm install; then
  echo "👹 Oops! Failed to npm install"

  exit 1
fi

echo "[INFO] Build"
if ! npm run build; then
  echo "👹 Oops! Failed to build"

  exit 1
fi

echo "[INFO] Clear cache"
if ! docker compose exec -it redis bash -c 'redis-cli flushall'; then
  echo "⚠️   Warning: Failed to clear cache"
fi

echo "[INFO] Clear mongodb"
if ! mongosh mongodb://localhost:27017/droidscord -u root -p root --authenticationDatabase admin --eval 'db.queries.remove({})'; then
  echo "⚠️  Warning: Failed to clear mongo db"
fi

if ! docker compose ps --format "{{.Service}} {{.State}}" | grep 'llm_indexer running' || ! docker compose ps --format "{{.Service}} {{.State}}" | grep 'discordjs-bot'; then
  echo "⚠️  Warrning: Docker compose stack is down"
  echo "🤖 Should start compose stack, be patient..."

  if ! docker compose up -d; then
    echo "👹 Oops! Failed to start compose stack"

    exit 1
  fi
fi

if ! docker compose restart; then
  echo "👹 Oops! Failed to restart docker compose"

  exit 1
fi
