name: Update

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest

    steps:
      - name: Connect remote & update
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd /home/discord/droidscord
            ./scripts/update
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
