name: Update

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ls -la
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
